# Generated by Django 3.1.2 on 2020-10-25 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uni_app', '0002_department_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='uni_app.subject'),
        ),
        migrations.AlterField(
            model_name='submittedassignment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
