# Generated by Django 3.1.2 on 2020-10-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uni_app', '0001_initial'),
        ('accounts', '0002_auto_20201025_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uni_app.university'),
        ),
    ]
